spring:
  http:
    encoding:
        charset: UTF-8
        enabled: true
        force: true
  # Redis Config
  redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      password:
  # Rabbitmq Config
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: dev
      password: ENC(BJiagLixFDJphPF0fw/6Tw==)
      publisher-confirms: true
      publisher-returns: true
      template.mandatory: true
      listener:
           concurrency: 2      #最小消息监听线程数
           max-concurrency: 2  #最大消息监听线程数
  # Quartz
  quartz:
      #相关属性配置
      properties:
        org:
          quartz:
            scheduler:
              instanceName: NewEagleScheduler
              instanceId: AUTO
            jobStore:
              class: org.quartz.impl.jdbcjobstore.JobStoreTX
              driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
              tablePrefix: n_qrtz_
              isClustered: true
              clusterCheckinInterval: 10000
              useProperties: false
            threadPool:
              class: org.quartz.simpl.SimpleThreadPool
              threadCount: 10
              threadPriority: 5
              threadsInheritContextClassLoaderOfInitializingThread: true
      #数据库方式
      job-store-type: jdbc
      #初始化表结构
      jdbc:
        initialize-schema: never
  # Datasource
  datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/neweagle-api?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
        username: root
        password: ENC(BJiagLixFDJphPF0fw/6Tw==)
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 20
        initial-size: 1
        min-idle: 3
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x' FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,log4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000

# Security
security:
  jwt:
    secret: k09BQnaF
    expiration: 1728000 #token过期时间

# Server
server:
  port: 80
  tomcat:
    accesslog:
      debug: true #请求响应数据调试
      uri-encoding: UTF-8

# Jasypt
jasypt:
  encryptor:
    password: BdaObXaELAA

#Mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/com/neweagle/api/module/*/mapper/xml/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.neweagle.api.module.*.entity
  typeEnumsPackage: com.neweagle.api.comm.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
    #key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
#    #自定义sql注入器,不在推荐使用此方式进行配置,请使用自定义bean注入
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#    #自定义填充策略接口实现,不在推荐使用此方式进行配置,请使用自定义bean注入
#    meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

